/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package com.ul;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JDialog;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

import com.DAO.HoaDonDAO;
import com.DAO.HDCTDAO;
import com.DAO.SanPhamDAO;
import com.entity.HDCT;
import com.entity.HoaDon;
import com.entity.SanPham;
import com.ul.HoaDonPanel;
import com.utils.Message;

/**
 *
 * @author korea
 */
public class BanHangPanel extends javax.swing.JPanel {

    /** Creates new form BanHangPanel */
    public BanHangPanel() {
        initComponents();
        init();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSanPham = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        pnlTrangThaiHoaDon5 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        pnlTaoHD = new javax.swing.JPanel();
        pnlHoaDon = new com.ul.HoaDonPanel();

        pnlSanPham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        javax.swing.GroupLayout pnlSanPhamLayout = new javax.swing.GroupLayout(pnlSanPham);
        pnlSanPham.setLayout(pnlSanPhamLayout);
        pnlSanPhamLayout.setHorizontalGroup(
            pnlSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSanPhamLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSanPhamLayout.setVerticalGroup(
            pnlSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSanPhamLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pnlTrangThaiHoaDon5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(tblHoaDon);

        javax.swing.GroupLayout pnlTrangThaiHoaDon5Layout = new javax.swing.GroupLayout(pnlTrangThaiHoaDon5);
        pnlTrangThaiHoaDon5.setLayout(pnlTrangThaiHoaDon5Layout);
        pnlTrangThaiHoaDon5Layout.setHorizontalGroup(
            pnlTrangThaiHoaDon5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrangThaiHoaDon5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pnlTrangThaiHoaDon5Layout.setVerticalGroup(
            pnlTrangThaiHoaDon5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTrangThaiHoaDon5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pnlTaoHD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlTaoHD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlTaoHD.add(pnlHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTrangThaiHoaDon5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTaoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTaoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlTrangThaiHoaDon5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void init() {
        taoHoaDon();
        fillTableSP();
        fillTableHD();
        chonSP();
        xoaSP();
    }
    private SanPhamDAO daoSP = new SanPhamDAO();
    private HoaDonDAO daoHD = new HoaDonDAO();
    private HDCTDAO daoHDCT = new HDCTDAO();

    private void fillTableHD() {
        try{
            String header[] = {"Mã Người tạo","Mã HD","Ngày tạo","Trạng thái","PTTT","Tổng tiền"};
            DefaultTableModel model = new DefaultTableModel(header, 0);
            tblHoaDon.setModel(model);
            List<HDCT> list = daoHDCT.selectAll();
            for(HDCT hdct : list){
                HoaDon h = daoHD.selectByID(hdct.getMaHD());
                Double tt = hdct.getSoLuong() * hdct.getDonGia();
                Object[] row = {h.getMaNV(),h.getMaHD(),h.getNgayTao(),h.getTrangThai(),h.getPttt(),tt};
                model.addRow(row);
            }
        }catch (Exception e) {
            e.printStackTrace();
            Message.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
    private void fillTableSP() {
        String header[] = {"Mã SP", "Tên SP", "Mã Loại", "Size", "Trạng thái", "Số Lượng", "Hình ảnh"};
        DefaultTableModel model = new DefaultTableModel(header, 0);
        tblSanPham.setModel(model);
        try {
            List<SanPham> list = daoSP.selectAll();
            for (SanPham sp : list) {
                Object[] row = {
                    sp.getMaSP(), sp.getTenSP(), sp.getMaLoai(), sp.getSize(), sp.getTrangThai(), sp.getSoLuong(), sp.getHinhAnh()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            Message.alert(this, "Lỗi truy vấn dữ liệu!");
            e.printStackTrace();

        }
    }
    int row = -1;
    List<String> maSPList = new ArrayList<String>();
    private void chonSP() {
        final JPopupMenu popupMenu = new JPopupMenu();
        JMenuItem addItem = new JMenuItem("Thêm sản phẩm");
        addItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                row = tblSanPham.getSelectedRow();
                String maSP =(String) tblSanPham.getValueAt(row, 0);
                maSPList.add(maSP);
                fillTableSL(maSPList);
            }
        });
        popupMenu.add(addItem);
        tblSanPham.setComponentPopupMenu(popupMenu);
    }
    private void xoaSP() {
        final JPopupMenu popupMenu = new JPopupMenu();
        JMenuItem addItem = new JMenuItem("Xóa sản phẩm");
        addItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                row = tblSanPham.getSelectedRow();
                String maSP =(String) tblSanPham.getValueAt(row, 0);
                maSPList.remove(maSP);
                fillTableSL(maSPList);
            }
        });
        popupMenu.add(addItem);
        HoaDonPanel.tblSoLuongSP.setComponentPopupMenu(popupMenu);
    }
    
    private void fillTableSL(List<String> maSP) {
        String []header = {"Mã SP","Tên SP","Size","Đơn Giá","Số Lượng","Tổng tiền"};
        DefaultTableModel model = new DefaultTableModel(header,0);
        HoaDonPanel.tblSoLuongSP.setModel(model);
        List<SanPham> list = daoSP.themSP(maSP);
        int soLuong = 1;
        for(SanPham sp : list){
            Double tt = soLuong * sp.getGiaSP();
            Object[] row = {sp.getMaSP(),sp.getTenSP(),sp.getSize(),sp.getGiaSP(),soLuong,tt};
            model.addRow(row);
        }
    }
    
    private void taoHoaDon() {
        JPopupMenu pmnHD = new JPopupMenu();
        JMenuItem mniTaoHD = new JMenuItem("Tạo hóa đơn");
        pmnHD.add(mniTaoHD);
        pnlHoaDon.setVisible(false);
        pnlTaoHD.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e){
                if(SwingUtilities.isRightMouseButton(e)){
                    pmnHD.show(pnlTaoHD,e.getX(),e.getY());
                }
            }
        });

        mniTaoHD.addActionListener(new ActionListener() { 
            @Override
            public void actionPerformed(ActionEvent e) {
                // TODO Auto-generated method stub
                pnlHoaDon.setVisible(true);
                
            }
         });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private com.ul.HoaDonPanel pnlHoaDon;
    private javax.swing.JPanel pnlSanPham;
    private javax.swing.JPanel pnlTaoHD;
    private javax.swing.JPanel pnlTrangThaiHoaDon5;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblSanPham;
    // End of variables declaration//GEN-END:variables

}
